Fix GHA

diff --git a/.github/workflows/deploy_to_ghcr.yml b/.github/workflows/deploy_to_ghcr.yml
--- a/.github/workflows/deploy_to_ghcr.yml
+++ b/.github/workflows/deploy_to_ghcr.yml
@@ -33,10 +33,25 @@ jobs:
     - name: Check Container Status
       run: |
         container_status=$(docker inspect --format='{{.State.Status}}' osaa-mvp-test)
-        if [ "$container_status" != "exited" ] || [ "$(docker inspect --format='{{.State.ExitCode}}' osaa-mvp-test)" != "0" ]; then
-          echo "Container failed to run correctly"
+        exit_code=$(docker inspect --format='{{.State.ExitCode}}' osaa-mvp-test)
+        error_log=$(docker logs osaa-mvp-test 2>&1)
+        
+        echo "Container Status: $container_status"
+        echo "Exit Code: $exit_code"
+        
+        if [ "$container_status" != "exited" ]; then
+          echo "Error: Container did not complete execution"
+          echo "$error_log"
           exit 1
         fi
+        
+        if [ "$exit_code" -ne 0 ]; then
+          echo "Error: Container exited with non-zero status code"
+          echo "$error_log"
+          exit 1
+        fi
+        
+        echo "Container ran successfully"
 
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v3
