Add env vars back in

diff --git a/.github/workflows/run_from_ghcr.yml b/.github/workflows/run_from_ghcr.yml
--- a/.github/workflows/run_from_ghcr.yml
+++ b/.github/workflows/run_from_ghcr.yml
@@ -20,20 +20,45 @@ jobs:
       env:
         TARGET: ${{ secrets.TARGET || 'dev' }}
         GATEWAY: ${{ secrets.GATEWAY || 'shared_state' }}
-        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-1' }}
-      run: docker compose run --rm pipeline transform
-      continue-on-error: true
-
-    - name: Check Container Logs
-      run: docker logs osaa-mvp-test
+        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION || 'us-east-2' }}
+      run: |
+        docker run --name osaa-mvp-test \
+          -e TARGET=$TARGET \
+          -e GATEWAY=$GATEWAY \
+          -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
+          -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
+          -e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION \
+          -e S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME || 'osaa-mvp' }} \
+          -e USERNAME=${{ secrets.USERNAME || 'osaa-mvp-user' }} \
+          -e POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
+          -e POSTGRES_PORT=${{ secrets.POSTGRES_PORT || '5432' }} \
+          -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
+          -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
+          -e POSTGRES_DB=${{ secrets.POSTGRES_DB || 'postgres' }} \
+          pipeline transform
 
     - name: Check Container Status
       run: |
         container_status=$(docker inspect --format='{{.State.Status}}' osaa-mvp-test)
-        if [ "$container_status" != "exited" ] || [ "$(docker inspect --format='{{.State.ExitCode}}' osaa-mvp-test)" != "0" ]; then
-          echo "Container failed to run correctly"
+        exit_code=$(docker inspect --format='{{.State.ExitCode}}' osaa-mvp-test)
+        error_log=$(docker logs osaa-mvp-test 2>&1)
+        
+        echo "Container Status: $container_status"
+        echo "Exit Code: $exit_code"
+        
+        if [ "$container_status" != "exited" ]; then
+          echo "Error: Container did not complete execution"
+          echo "$error_log"
           exit 1
         fi
+        
+        if [ "$exit_code" -ne 0 ]; then
+          echo "Error: Container exited with non-zero status code"
+          echo "$error_log"
+          exit 1
+        fi
+        
+        echo "Container ran successfully"
 
     - name: Cleanup
       if: always()
